# Generated by Django 3.2.9 on 2023-05-09 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='cluster_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='is_churned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Пайыз мөлшерлемесі 0 - 100 дейін', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='interest_calculation_per_year',
            field=models.PositiveSmallIntegerField(help_text='Жылына пайыздар қанша рет есептелу керек', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='interest_start_date',
            field=models.DateField(blank=True, help_text='Пайыз есептеу басталатын ай', null=True),
        ),
    ]
