# Generated by Django 3.2.9 on 2023-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230509_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccountClusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100)),
            ],
        ),
    ]
