# Generated by Django 3.2 on 2023-05-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230513_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBankAccountClusters',
            new_name='UserBankAccountCluster',
        ),
        migrations.RenameModel(
            old_name='UserBankAccountProducts',
            new_name='UserBankAccountProduct',
        ),
    ]
