# Generated by Django 3.2 on 2023-05-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230513_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userbankaccountproduct'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='cluster_label',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userbankaccountcluster'),
        ),
    ]
