# Generated by Django 3.2 on 2023-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230513_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccountcluster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankaccountproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
